<div class="container-fluid">
  <div class="row-fluid">
    <div class="span3">
      <div class="well sidebar-nav">
        <ul class="nav nav-list">
          <li class="nav-header">My Gamitu.de</li>
          <li><a href="/account">Home</a></li>
          <li><a href="/account/edit">My Account</a></li>
          <li class="active"><a href="/account/google">Google</a></li>
          <li><a href="/account/twitter">Twitter</a></li>
          <li><a href="/account/foursquare">Foursquare</a></li>
          <li class="nav-header">Location</li>
          <li><a href="/account/data">Location Data</a></li>
          <li><a href="/account/badges">Badges</a></li>
          <li><a href="/account/stats">Statistics</a></li>
        </ul>
      </div><!--/.well -->
    </div><!--/span-->
    <div class="span9">

      <div class="row-fluid">
        <div class="span12">
          <h2>Google Accounts</h2>
          <p>Given that Gamitu.de is built upon Google oAuth & Google Latitude, a Google account is required to use this service.</p>
        </div><!--/span-->
      </div><!--/row-->
    </div><!--/span-->
  </div><!--/row-->
<hr>

<footer>
  <p>&copy; <?=$this->get_author();?> <?=date("Y");?></p>
</footer>

