<div class="container-fluid">
  <div class="row-fluid">
    <?php require("account.navigation.phtml"); ?>

    <div class="span9">
      <div class="row-fluid">
        <div class="span12">
          <h2><?=t("Foursquare Locations")?>:</h2>
        </div><!--/span-->
      </div><!--/row-->
    </div><!--/span-->
    <div class="span9">
      <div class="row-fluid">
        <div class="span12">
          <?=$this->table($this->venue_history); ?>
        </div><!--/span-->
      </div><!--/row-->
    </div><!--/span-->
  </div>
<hr>

<footer>
  <p>&copy; <?=$this->get_author();?> <?=date("Y");?></p>
</footer>

