<div class="container-fluid">
  <div class="row-fluid">
    <?php require("account.navigation.phtml"); ?>

    <div class="span9">
      <div class="row-fluid">
        <div class="span12">
          <h2><?=t("Foursquare Locations")?>:</h2>
        </div><!--/span-->
      </div><!--/row-->
    </div><!--/span-->
    <div class="span9">
      <div class="row-fluid">
        <?php foreach($this->venue_history as $venue): ?>
          <!--
          <?php var_dump($venue); ?>
          -->
          <div class="span3">
            <dl>
              <dt><?=t("Name")?></dt>
              <dd><?=$venue->venue->name?></dd>
              <dt><?=t("ID")?></dt>
              <dd><?=$venue->venue->id?></dd>
              <dt><?=t("City")?></dt>
              <dd><?=$venue->venue->location->city?></dd>
              <dt><?=t("Country")?></dt>
              <dd><?=$venue->venue->location->country?></dd>
            </dl>
          </div><!--/span-->
        <?php endforeach; ?>
      </div><!--/row-->
    </div><!--/span-->
  </div><!--/row-->
<hr>

<footer>
  <p>&copy; <?=$this->get_author();?> <?=date("Y");?></p>
</footer>

