<div class="span3">
  <div class="well sidebar-nav">
    <ul class="nav nav-list">
      <li class="nav-header">My Gamitu.de</li>
      <li><?=$this->l("Home", "account"); ?></li>
      <li><?=$this->l("My Account", "account", "edit"); ?></li>
      <li><?=$this->l("Google", "account", "google"); ?></li>
      <li><?=$this->l("Twitter", "account", "twitter"); ?></li>
      <li><?=$this->l("Foursquare", "account", "foursquare"); ?></li>
      <li class="nav-header">Location</li>
      <li><?=$this->l("Data", "account", "data"); ?></li>
      <li><?=$this->l("Badges", "account", "badges"); ?></li>
      <li><?=$this->l("Statistics", "account", "stats"); ?></li>
      <li class="nav-header">Utilities</li>
      <li><?=$this->l("Scheduled Checkins", "account", "scheduled-checkins")?></li>
    </ul>
  </div><!--/.well -->
</div><!--/span-->