<?php var_dump($_SERVER);exit; ?>
<div class="span3">
  <div class="well sidebar-nav">
    <ul class="nav nav-list">
      <li class="nav-header">My Gamitu.de</li>
      <li><a href="/account">Home</a></li>
      <li class="active"><a href="/account/edit">My Account</a></li>
      <li><a href="/account/google">Google</a></li>
      <li><a href="/account/twitter">Twitter</a></li>
      <li><a href="/account/foursquare">Foursquare</a></li>
      <li class="nav-header">Location</li>
      <li><a href="/account/data">Location Data</a></li>
      <li><a href="/account/badges">Badges</a></li>
      <li><a href="/account/stats">Statistics</a></li>
    </ul>
  </div><!--/.well -->
</div><!--/span-->