<div class="container-fluid">
  <div class="row-fluid">
    <?php require("account.navigation.phtml"); ?>

    <div class="span9">
      <div class="row-fluid">
        <div class="span12">
          <h2>Twitter Accounts</h2>
        </div><!--/span-->
      </div><!--/row-->
    </div><!--/span-->
  </div><!--/row-->
<hr>

<footer>
  <p>&copy; <?=$this->get_author();?> <?=date("Y");?></p>
</footer>

