<div class="container-fluid">
  <div class="row-fluid">
    <?php require("account.navigation.phtml"); ?>

    <div class="span9">
      <div class="row-fluid">
        <div class="span12">
          <h2><?= t("Google Accounts") ?></h2>

          <p><?= t("Given that Gamitu.de is built upon Google oAuth & Google Latitude, a Google account is required to use this service.") ?></p>
        </div>
        <!--/span-->
      </div>
      <!--/row-->
    </div>
    <!--/span-->
  </div>
  <!--/row-->
  <hr>

  <footer>
    <p>&copy; <?= $this->get_author(); ?> <?= date("Y"); ?></p>
  </footer>

