<?php var_dump($_SERVER);exit; ?>
<div class="span3">
  <div class="well sidebar-nav">
    <ul class="nav nav-list">
      <li class="nav-header">My Gamitu.de</li>
      <li><?=$this->_view->l("Home", "account"); ?></li>
      <li><?=$this->_view->l("My Account", "account", "edit"); ?></li>
      <li><?=$this->_view->l("Google", "account", "google"); ?></li>
      <li><?=$this->_view->l("Twitter", "account", "twitter"); ?></li>
      <li><?=$this->_view->l("Foursquare", "account", "foursquare"); ?></li>
      <li class="nav-header">Location</li>
      <li><?=$this->_view->l("Data", "account", "data"); ?></li>
      <li><?=$this->_view->l("Badges", "account", "badges"); ?></li>
      <li><?=$this->_view->l("Statistics", "account", "stats"); ?></li>
    </ul>
  </div><!--/.well -->
</div><!--/span-->