<!-- Main hero unit for a primary marketing message or call to action -->

<script type="text/javascript">
  jQuery(document).ready(function () {
    var myLatlng = new google.maps.LatLng(<?=$this->lat?>, <?=$this->long?>);

    var mapOptions = {
      center: myLatlng,
      zoom: 14,
      mapTypeId: google.maps.MapTypeId.ROADMAP
    };
    var map = new google.maps.Map(document.getElementById("map_canvas"), mapOptions);

    var marker = new google.maps.Marker({
      position: myLatlng,
      map: map,
      title: "Here!"
    });
  });
</script>

<div class="big_map_canvas" id="map_canvas"></div>
<hr>

<footer>
  <p>
    &copy;
    <?= $this->get_author(); ?>
    <?= date("Y"); ?>
  </p>
</footer>

