<div class="container-fluid">
  <div class="row-fluid">
    <?php require("account.navigation.phtml"); ?>

    <div class="span9">
      <div class="row-fluid">
        <div class="span12">
          <h1>
            <?php echo $this->user->get_username(); ?>'s Travel
            between <?php echo date("Y-m-d H:i:s", $this->start) ?>
            and <?php echo date("Y-m-d H:i:s", $this->end) ?>
          </h1>
        </div>

        <div class="span12">
          <form action="" method="POST">
            <div class="control-group">
              <label class="control-label"><?php echo t("Date Range"); ?>:</label>
              <div class="controls">
                <div class="btn-group">
                  <input name="range" type="submit" class="btn" value="Day">
                  <input name="range" type="submit" class="btn" value="Week">
                  <input name="range" type="submit" class="btn" value="Month">
                  <input name="range" type="submit" class="btn" value="Year">
                </div>
              </div>
            </div>
            <div class="control-group">
              <label class="control-label"><?php echo t("Date Point Position"); ?>:</label>
              <div class="controls">
                <div class="btn-group">
                  <input name="offset" type="submit" class="btn" value="Backwards">
                  <input name="offset" type="submit" class="btn" value="Forwards">
                </div>
              </div>
            </div>
            <div class="control-group">
              <label class="control-label"><?php echo t("Share this map"); ?>:</label>
              <div class="controls">
                <input value="<?php echo "https://gamitu.de/map/view-journey?user_id={$this->user->uid}&range={$this->range_days}&offset={$this->offset_days}"; ?>"/>
              </div>
            </div>
          </form>
        </div>

        <div class="span12">
          <?php if (count($this->points) > 0): ?>

            <div class="big_map_canvas" id="map_canvas"></div>

            <script>
              var map;
              function initialize() {
                var mapOptions = {
                  zoom: 8,
                  center: <?php echo end($this->points)->get_google_maps_lat_lng(); ?>,
                  mapTypeId: google.maps.MapTypeId.ROADMAP
                };
                map = new google.maps.Map(
                  document.getElementById('map_canvas'),
                  mapOptions
                );

                var routeCoordinates = [
                  <?php foreach($this->points as $point): ?>
                  <?php echo $point->get_google_maps_lat_lng(); ?>,
                  <?php endforeach; ?>
                ];

                var routePath = new google.maps.Polyline({
                  path: routeCoordinates,
                  strokeColor: '#FF0000',
                  strokeOpacity: 1.0,
                  strokeWeight: 2
                });

                routePath.setMap(map);

              }
              jQuery(document).ready(function () {
                google.maps.event.addDomListener(window, 'load', initialize);
              });

            </script>
            <?php if(user::get_current_user()): ?>
              <?php if (user::get_current_user()->get_uid() == 1): ?>
                <?php krumo($this); ?>
              <?php endif; ?>
            <?php endif; ?>
          <?php endif; ?>
        </div>
      </div>
    </div>
  </div>

  <hr>

  <footer>
    <p>&copy; <?= $this->get_author(); ?> <?= date("Y"); ?></p>
  </footer>

