<?php krumo($this); ?>
<script type="text/javascript">
  jQuery(document).ready(function () {
    var map;

    function initialize() {
      var mapOptions = {
        zoom: 8,
        center: new google.maps.LatLng(-34.397, 150.644),
        mapTypeId: google.maps.MapTypeId.ROADMAP
      };
      map = new google.maps.Map(
        document.getElementById('map-canvas'),
        mapOptions
      );
    }

    google.maps.event.addDomListener(window, 'load', initialize);

  });
</script>

<div class="big_map_canvas" id="map_canvas"></div>
<hr>

<footer>
  <p>
    &copy;
    <?= $this->get_author(); ?>
    <?= date("Y"); ?>
  </p>
</footer>

