<h1><?php echo $this->user->get_username();?>'s Travel between <?php echo date("Y-m-d H:i:s", $this->start) ?> and <?php echo date("Y-m-d H:i:s", $this->end) ?> </h1>

<div class="big_map_canvas" id="map_canvas"></div>
<hr>

<script>
  var map;
  function initialize() {
    var mapOptions = {
      zoom: 8,
      center: <?php echo end($this->points)->get_google_maps_lat_lng(); ?>,
      mapTypeId: google.maps.MapTypeId.ROADMAP
    };
    map = new google.maps.Map(
      document.getElementById('map_canvas'),
      mapOptions
    );

    var routeCoordinates = [
      <?php foreach($this->points as $point): ?>
        <?php echo $point->get_google_maps_lat_lng(); ?>,
      <?php endforeach; ?>
    ];

    var routePath = new google.maps.Polyline({
      path: routeCoordinates,
      strokeColor: '#FF0000',
      strokeOpacity: 1.0,
      strokeWeight: 2
    });

    routePath.setMap(map);

  }
  jQuery(document).ready(function(){
    google.maps.event.addDomListener(window, 'load', initialize);
  });

</script>

<?php krumo($this); ?>

<footer>
  <p>
    &copy;
    <?= $this->get_author(); ?>
    <?= date("Y"); ?>
  </p>
</footer>

