<div class="container">

	<table class="table table-bordered table-compact">
		<thead>
			<tr>
				<th>Date &amp; Time</th>
				<th>Delta</th>
				<th>Latitude &amp; Longitude</th>
				<th>Delta</th>
			</tr>
		</thead>
		<tbody>
			<?php foreach($this->feed as $position):?>
				<?php 
				$classes = array();
				$delta = $this->deltas[$position->get_pid()];
				if($delta->delta_latlong <> 0){
					$classes[] = "success";
				}
				?>
				<tr class="<?=implode(" ",$classes)?>">
					<td>
						<?=date("Y-m-d H:i:s", $position->get_timestamp_ms());?>
					</td>
					<td>
						<?=$delta->delta_timestamp_ms?round($delta->delta_timestamp_ms):'N/A'?> sec
					</td>
					<td>
						<?=$position->get_latitude();?>,<?=$position->get_longitude();?>
					</td>
					<td>
						<?=isset($delta->delta_lat)?$delta->delta_lat:'0'?>,
						<?=isset($delta->delta_long)?$delta->delta_long:'0'?>
					</td>
				</tr>
				<?php $prev = $position;?>
			<?php endforeach; ?>
		</tbody>
	</table>
	
	<hr>

	<footer>
		<p>&copy; <?=$this->get_author();?> <?=date("Y");?></p>
	</footer>

</div> <!-- /container -->