<div class="container">

	<table class="table table-bordered table-compact">
		<thead>
			<tr>
				<th>Date &amp; Time</th>
				<th>Delta</th>
				<th>Latitude &amp; Longitude</th>
				<th>Delta</th>
			</tr>
		</thead>
		<tbody>
			<?php foreach($this->feed as $position):?>
				<tr>
					<td>
						<?=date("Y-m-d H:i:s", $position->get_timestamp_ms());?>
					</td>
					<td>
						<?php if($prev):?>
							<?=($position->get_timestamp_ms() - $prev->get_timestamp_ms())?>
						<?php endif; ?>
					</td>
					<td>
						<?=$position->get_latitude();?>,<?=$position->get_longitude();?>
					</td>
					<td>
						<?php if($prev):?>
							<?=($position->get_latitude() - $prev->get_latitude());?>,<?=($position->get_longitude() - $prev->get_longitude());?>
						<?php endif; ?>
					</td>
				</tr>
				<?php $prev = $position;?>
			<?php endforeach; ?>
		</tbody>
	</table>
	
	<hr>

	<footer>
		<p>&copy; <?=$this->get_author();?> <?=date("Y");?></p>
	</footer>

</div> <!-- /container -->