<!DOCTYPE html>
<html lang="en">
	<head>
		<meta charset="utf-8">
		<meta http-equiv="Content-type" value="text/html; charset=UTF-8" />
		<title><?php echo $this->get_title();?></title>
		<meta name="viewport" content="width=device-width, initial-scale=1.0">
		<meta name="description" content="<?php echo $this->get_description();?>">
		<meta name="author" content="<?php echo $this->get_author();?>">

		<!-- Le styles -->
		<link href="/css/bootstrap.css" rel="stylesheet">
		<style type="text/css">
			body {
				padding-top: 60px;
				padding-bottom: 40px;
			}
		</style>
		<link href="/css/bootstrap-responsive.css" rel="stylesheet">

		<!-- HTML5 shim, for IE6-8 support of HTML5 elements -->
		<!--[if lt IE 9]>
			<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
		<![endif]-->

		<!-- Fav and touch icons -->
		<link rel="shortcut icon" href="/ico/favicon.ico">
		<link rel="apple-touch-icon-precomposed" sizes="144x144" href="/ico/apple-touch-icon-144-precomposed.png">
		<link rel="apple-touch-icon-precomposed" sizes="114x114" href="/ico/apple-touch-icon-114-precomposed.png">
		<link rel="apple-touch-icon-precomposed" sizes="72x72" href="/ico/apple-touch-icon-72-precomposed.png">
		<link rel="apple-touch-icon-precomposed" href="/ico/apple-touch-icon-57-precomposed.png">
	</head>

	<body>

		<?php require_once("navigation.phtml"); ?>

		<?php $this->render_page(); ?>

		<!-- Le javascript
		================================================== -->
		<!-- Placed at the end of the document so the pages load faster -->
		<script src="/js/jquery.js"></script>
    	<script src="/js/bootstrap-transition.js"></script>
    	<script src="/js/bootstrap-alert.js"></script>
    	<script src="/js/bootstrap-modal.js"></script>
    	<script src="/js/bootstrap-dropdown.js"></script>
    	<script src="/js/bootstrap-scrollspy.js"></script>
    	<script src="/js/bootstrap-tab.js"></script>
    	<script src="/js/bootstrap-tooltip.js"></script>
    	<script src="/js/bootstrap-popover.js"></script>
    	<script src="/js/bootstrap-button.js"></script>
    	<script src="/js/bootstrap-collapse.js"></script>
    	<script src="/js/bootstrap-carousel.js"></script>
    	<script src="/js/bootstrap-typeahead.js"></script>
	</body>
</html>
