<div class="navbar navbar-inverse navbar-fixed-top">
	<div class="navbar-inner">
		<div class="fluid-container">
			<a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
			</a>
			<a class="brand" href="/"><?php echo $this->get_sitename(); ?></a>
			<div class="nav-collapse collapse">
				<ul class="nav">
					<li class="active"><a href="/">Home</a></li>
          <?php if(user::is_loggedin()):?>
          <li><a href="/account">My Dashboard</a></li>
          <?php endif; ?>
				</ul>
				<ul class="nav pull-right">
					<?php if(user::is_loggedin()):?>
						<li><a href="/account">Hello, <?=user::get_current_user()->get_username()?></a></li>
            <li class="icon"><img src="<?=user::get_current_user()->get_face()?>"/></li>
						<li><a href="/user/logout">Sign out</a></li>
					<?php else:?>
						<li><a href="/user/login">Sign in</a></li>
					<?php endif; ?>
				</ul>
				
			</div><!--/.nav-collapse -->
		</div>
	</div>
</div>