<div class="navbar navbar-inverse navbar-fixed-top">
	<div class="navbar-inner">
		<div class="container">
			<a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
			</a>
			<a class="brand" href="/"><?php echo $this->get_sitename(); ?></a>
			<div class="nav-collapse collapse">
				<ul class="nav">
					<li class="active"><a href="/">Home</a></li>
					
					<li><a href="#contact">Contact</a></li>
					<li class="dropdown">
						<a href="#" class="dropdown-toggle" data-toggle="dropdown">Devel Buttans <b class="caret"></b></a>
						<ul class="dropdown-menu">
							<li><a href="/user/update_access_key">Update Google Access Key Manually</a></li>
							<li><a href="#">Another action</a></li>
							<li><a href="#">Something else here</a></li>
							<li class="divider"></li>
							<li class="nav-header">Nav header</li>
							<li><a href="#">Separated link</a></li>
							<li><a href="#">One more separated link</a></li>
						</ul>
					</li>
				</ul>
				<ul class="nav pull-right">
					<?php if(user::is_loggedin()):?>
						<li><a href="/user/edit">Hello, <?=user::get_current_user()->get_username()?></a></li>
						<li><a href="/user/logout">Sign out</a></li>
					<?php else:?>
						<li><a href="/user/login">Sign in</a></li>
					<?php endif; ?>
				</ul>
				
			</div><!--/.nav-collapse -->
		</div>
	</div>
</div>